version: '3.8'
services:
  php-api:
    build: ./Gestion de patrocinadores y compra
    ports:
      - "5003:5003"
    volumes:
      - ./Gestion de patrocinadores y compra:/var/www/html
  python-api:
    build: ./Gestion_entrega_api
    ports:
      - "5002:5002"
    volumes:
      - ./Gestion_entrega_api:/app
  dotnet-api:
    build: ./KioscoDigital.WebAPI
    ports:
      - "5001:5001"
    volumes:
      - ./KioscoDigital.WebAPI:/app
